### ISSUE TITLE
Error when running script on aep version 5.1.2

### ISSUE THREAD

**Issue by 2ni** [kersing/multitech-installer#27]
When running the installer I get the following errors on the multitech aep:
```
Stopping existing forwarder
Stopping ttn-packet-forwarder: start-stop-daemon: warning: failed to kill 3979: No such process
killall: mp_pkt_fwd: no process killed
OK
Get up-to-date TTN configuration for packet forwarder

module.js:340
    throw err;
          ^
Error: Cannot find module '/opt/lora/merge.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:945:3
Starting ttn-packet-forwarder: OK
The installation is now complete.
Check the gateway output using:
tail -f /var/log/lora-pkt-fwd.log
(It might take some minutes for the first output to appear!)
Check the gateways last seen status in the TTN console after
a few minutes to verify the setup is working correctly
```

Anything I'm doing wrong?

**Comment by 2ni** [comment]
Ok, will try again then. Thx!
